import { chromium } from 'playwright';
import { readdirSync } from 'node:fs';
const browsersRoot = process.env.PLAYWRIGHT_BROWSERS_PATH || '/opt/pw-browsers';
const chromeDir = readdirSync(browsersRoot).find(d => /^chromium-/.test(d));
const BASE = 'http://127.0.0.1:4173';
const b = await chromium.launch({ executablePath: chromeDir ? `${browsersRoot}/${chromeDir}/chrome-linux/chrome` : undefined });
const p = await b.newPage({ viewport: { width: 1440, height: 1000 } });
p.on('dialog', d => d.accept());
await p.goto(`${BASE}?e2eReset=1`, { waitUntil: 'networkidle' });
await p.waitForTimeout(1500);
await p.getByRole('button', { name: /^Stock Intake$/i }).first().click().catch(()=>{});
await p.waitForTimeout(800);
// wipe all
await p.getByRole('button', { name: /^Wipe$/i }).click();
await p.waitForTimeout(500);
await p.getByRole('menuitem', { name: /Wipe All/i }).click();
await p.waitForTimeout(700);
await p.getByText(/I understand this will delete all inventory data/i).click();
await p.waitForTimeout(200);
await p.getByRole('button', { name: /Delete All Data/i }).click();
await p.waitForTimeout(3000);
await p.goto(BASE, { waitUntil: 'networkidle' });
await p.waitForTimeout(1500);
await p.getByRole('button', { name: /^Stock Intake$/i }).first().click().catch(()=>{});
await p.waitForTimeout(800);
// import menu
const byLabel = p.getByRole('button', { name: /^Import$/i }).first();
console.log('Import button visible:', await byLabel.isVisible().catch(()=>false));
if (await byLabel.isVisible().catch(()=>false)) await byLabel.click();
else await p.locator('button[aria-haspopup="menu"]').first().click();
await p.waitForTimeout(1000);
console.log('IMPORT MENU ITEMS:', JSON.stringify(await p.getByRole('menuitem').allInnerTexts().catch(()=>[])));
await p.screenshot({ path: 'probe-import-menu.png', fullPage: false });
await b.close();
