/**
 * TemplateDownload — "build your file from the standard, not from a colleague's
 * old copy."
 *
 * Sits next to the reports it belongs to (in the range menu) and inside the
 * import modals (at the point of upload). Both placements answer the same
 * question at the moment it's actually asked: *what shape should this file
 * be?* Answering it with a link to the current template is the difference
 * between an import that lands and an afternoon of re-keying.
 *
 * Files come from public/templates/, written by the same run that writes
 * templates/ (`npm run templates`), so what the app hands out can't drift
 * from what the tests parse. The SALES templates go one further: since
 * 2026-08 they are generated by calling the report writer itself
 * (scripts/generateSalesTemplates.ts), so they carry the report's exact
 * columns AND live formulas — fill in BP and SP and the row computes.
 */
import React from 'react';
import { FileDown } from 'lucide-react';
import { SHOW_TEMPLATE_DOWNLOADS } from '../lib/featureFlags';

export interface TemplateLink {
  /** File name inside public/templates/. */
  file: string;
  /** What the operator calls it. */
  label: string;
  /** One line on when to reach for this one. */
  hint?: string;
}

const BASE = 'templates';

/**
 * The template block for a report menu — a labelled divider plus one row per
 * template. Renders nothing when a report has no template to offer, so callers
 * can pass an empty list without special-casing.
 */
export default function TemplateDownload({
  templates,
  heading = 'Build a new file from',
}: {
  templates: TemplateLink[];
  heading?: string;
}) {
  // Gated here rather than at each of the six call sites: one guard, and a
  // future placement can't accidentally bypass it. See
  // SHOW_TEMPLATE_DOWNLOADS.
  if (!SHOW_TEMPLATE_DOWNLOADS) return null;
  if (!templates.length) return null;
  return (
    <div className="border-t border-slate-100 bg-slate-50/60">
      <p className="px-3 pt-2 pb-1 text-[9px] font-bold uppercase tracking-widest text-slate-400">
        {heading}
      </p>
      {templates.map(t => (
        <a
          key={t.file}
          href={`${import.meta.env.BASE_URL ?? '/'}${BASE}/${t.file}`}
          download={t.file}
          className="flex items-start gap-2 px-3 py-2 hover:bg-slate-50 transition-colors group"
        >
          <FileDown
            size={13}
            className="mt-0.5 flex-shrink-0 text-slate-400 group-hover:text-emerald-600 transition-colors"
          />
          <span className="min-w-0">
            <span className="block text-[11px] font-bold text-slate-700 group-hover:text-slate-900">
              {t.label}
            </span>
            {t.hint && (
              <span className="block text-[9px] font-mono text-slate-400 leading-tight">{t.hint}</span>
            )}
          </span>
        </a>
      ))}
    </div>
  );
}

// ── The catalogue, in one place ──────────────────────────────────────────────
// Referenced by both the report menus and the import modals so the two can't
// offer different files for the same job.


// Column counts are the REPORT's, because these files are generated from it —
// see scripts/generateSalesTemplates.ts. Every one carries live formulas on
// 200 primed rows: type a BP and an SP and the row fills itself in.
// salesTemplateFormulas.test.ts fails if a count here stops matching.
export const SALES_TEMPLATES: TemplateLink[] = [
  // All working sheets. Nothing here goes back INTO the app — sales are
  // recorded on screen through Mark Multiple Sold, which reconciles against
  // live stock; a spreadsheet route could not.
  {
    file: 'SALES_REPORT_TEMPLATE.xlsx',
    label: 'Sales template · all marketplaces',
    hint: 'one sheet per channel · live formulas',
  },
  { file: 'SALES_AMAZON_TEMPLATE.xlsx', label: 'Amazon only', hint: '31 columns · live formulas' },
  { file: 'SALES_BM_TEMPLATE.xlsx',     label: 'BM only',     hint: '28 columns · Customer Care £8.99' },
  { file: 'SALES_EBAY_TEMPLATE.xlsx',   label: 'eBay only',   hint: '34 columns · type Marketing + P. VAT' },
  { file: 'SALES_ONBUY_TEMPLATE.xlsx',  label: 'OnBuy only',  hint: '28 columns · no Quantity' },
  // Not Amazon's layout — Temu has its own schema, and it is the one channel
  // carrying a real Commission per row (its referral rate varies by category,
  // so the export reports the fee it actually charged). Commission VAT is NOT
  // read back: it derives as Commission x 20%.
  { file: 'SALES_TEMU_TEMPLATE.xlsx',   label: 'Temu only',   hint: '29 columns · own layout · Commission typed' },
];
