/**
 * generateSalesTemplates — the Sales templates, built FROM the Sales Report.
 *
 * Run: npx tsx scripts/generateSalesTemplates.ts
 *
 * Why this replaces the hand-written SALES_LAYOUTS in
 * generateImportTemplates.mjs: that script kept its own copy of every
 * marketplace's column list, and the copies drifted. The templates shipped
 * eBay's `0.2` / `NP(incl. PROMOTION)` and BM's `PayPal/Klarna Com` long
 * after the report had moved on, so an operator building a file from the
 * template produced something that did not look like the report at all.
 *
 * Here the templates are generated by calling the REAL report writer
 * (buildSalesWorkbookBuffer) and then emptying the rows. The header row,
 * the column order, the number formats and every per-row formula come from
 * the same code path that writes a live report, so they cannot disagree —
 * there is no second copy to keep in step.
 *
 * The formulas are LIVE. Type a BP and an SP into a row and Excel fills in
 * SP-BP, Marginal Tax, Commission, the VAT lines, GP, GP % and Total VAT NTP
 * on the spot. Each one is wrapped in a guard on the SP cell:
 *
 *     =IF($H5="","", <the report's formula, unchanged>)
 *
 * so an unfilled row shows an empty cell rather than 0 or #DIV/0!. The
 * expression inside the guard is byte-identical to what the report writes —
 * salesTemplateFormulas.test.ts strips the guard and compares.
 */
import ExcelJS from 'exceljs';
import { mkdirSync, existsSync, copyFileSync } from 'node:fs';
import { buildSalesWorkbookBuffer } from '../src/lib/clientReport';
import { MARKETPLACES } from '../src/types';
import type { Marketplace, Sale } from '../src/types';

const OUT = 'templates';
const PUBLIC_OUT = 'public/templates';
for (const dir of [OUT, PUBLIC_OUT]) if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

/** Blank rows primed with formulas, ready for the operator to type into. */
const BLANK_ROWS = 200;

/**
 * Flat per-sale charges the report writes as LITERAL values, not formulas —
 * they come off the fee schedule, not off the row. They have to survive the
 * hollowing-out: a primed row that lost them would compute a GP missing the
 * accessory pound (and, on BM, the £8.99 care fee), so the operator's own
 * spreadsheet would quietly disagree with the app.
 */
const CONSTANT_HEADERS = new Set(['Accessories', 'FVF', 'Customer Care Fees']);

/**
 * The worked example row, one per marketplace.
 *
 * These carry the SAME order numbers, IMEIs, SKUs, suppliers and prices the
 * templates have always shipped. That is not cosmetic: five E2E scripts
 * (e2eTemuMarketplace, e2eTemplateFillAndUpload, e2eBatchVsMarketplace,
 * e2eShsOrphanFlow, e2eUploadFlow) seed stock against these identities and
 * then upload the real template to prove the round trip. Inventing new
 * example rows here silently broke all five — the sale imported fine, it just
 * no longer matched the unit the script had put in stock.
 *
 * Change a price if the fee schedule moves. Do not change the identities.
 */
const EXAMPLE: Record<Marketplace, Partial<Sale>> = {
  AMAZON: { orderNumber: 'AMZ-5001', imei: '350100000000000', sku: 'IP13-128-MID',
            supplierName: 'MOBILE WHOLESALE LTD', buyPrice: 320, salePrice: 425, postage: 8 },
  BM:     { orderNumber: 'BM-7781', imei: '350100000015838', sku: 'S22-128-GRN',
            supplierName: 'PHONEBOX DIRECT', buyPrice: 240, salePrice: 329, postage: 8,
            paymentMode: 'Paypal' },
  EBAY:   { orderNumber: 'EB-3310', imei: '350100000023757', sku: 'IP13P-256-GRA',
            supplierName: 'CELLHUB TRADING', buyPrice: 520, salePrice: 679, postage: 8 },
  ONBUY:  { orderNumber: 'OB-9002', imei: '350100000031676', sku: 'PIX7-128-BLK',
            supplierName: 'NORTHSIDE STOCK', buyPrice: 275, salePrice: 359, postage: 8 },
  TEMU:   { orderNumber: 'PO-210-07053322437751959', imei: '350901801557294',
            sku: 'SG-A17-128GB-OB', supplierName: 'MHL',
            buyPrice: 55, salePrice: 83.99, postage: 6.30, commission: 3.87 },
};

const sale = (m: Marketplace, i: number, over: Partial<Sale> = {}): Sale => ({
  id: `${m}__TPL-${i}__35010000000${String(i).padStart(4, '0')}`,
  marketplace: m,
  orderNumber: `TPL-${i}`,
  imei: `35010000000${String(i).padStart(4, '0')}`,
  supplierName: 'EXAMPLE SUPPLIER',
  saleDate: '2026-08-01',
  quantity: 1, buyPrice: 0, salePrice: 0, postage: 0,
  spMinusBp: 0, marginalTax: 0, commission: 0, grossProfit: 0, gpPercent: 0,
  importBatchId: '', sourceFile: '', sourceRow: i, importedAt: '',
  createdAt: '', updatedAt: '', ownerId: 'shared',
  ...over,
} as Sale);

/** Build the live report, then hollow it out into a template. */
async function reportShapedWorkbook(): Promise<ExcelJS.Workbook> {
  const sales: Sale[] = [];
  for (const m of MARKETPLACES) {
    sales.push(sale(m, 1, { ...EXAMPLE[m], id: `${m}__EXAMPLE` }));
    for (let i = 2; i <= BLANK_ROWS + 1; i++) sales.push(sale(m, i));
  }
  const buf = await buildSalesWorkbookBuffer({
    sales, units: [], supplierMap: {}, opts: {} as never,
  });
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.load(buf as ArrayBuffer);
  return wb;
}

/** Column letter for a 1-based index. */
function letter(n: number): string {
  let s = '';
  while (n > 0) { const m = (n - 1) % 26; s = String.fromCharCode(65 + m) + s; n = (n - m - 1) / 26; }
  return s;
}

/**
 * Empty every primed row and guard its formulas.
 * Row 2 keeps the worked example; rows 3+ become blank-but-live.
 */
function hollowOut(ws: ExcelJS.Worksheet): void {
  const headers = ((ws.getRow(1).values ?? []) as unknown[])
    .slice(1).map(v => String(v ?? '').trim());
  const spCol = headers.indexOf('SP') + 1;
  if (spCol === 0) throw new Error(`${ws.name}: no SP column to guard on`);
  const spLetter = letter(spCol);

  ws.eachRow((row, n) => {
    if (n === 1) return;
    const isTotal = String(row.getCell(1).value ?? '').trim().toUpperCase() === 'TOTAL';
    if (isTotal) return;                       // the TOTAL row keeps its SUM()s
    const keepValues = n === 2;                // the worked example stays filled

    row.eachCell({ includeEmpty: true }, (cell, c) => {
      const v = cell.value as { formula?: string } | null;
      const isFormula = v && typeof v === 'object' && 'formula' in v && v.formula;
      if (isFormula) {
        // Guard on SP so an untouched row renders blank instead of 0 /
        // #DIV/0!, while the arithmetic inside stays exactly the report's.
        cell.value = { formula: `IF($${spLetter}${n}="","",${(v as {formula: string}).formula})` };
        return;
      }
      if (keepValues) return;
      // Flat fee-schedule charges stay; everything else the operator types.
      if (!CONSTANT_HEADERS.has(headers[c - 1])) cell.value = null;
    });
  });
}

/** A README the operator can actually act on. */
function addReadme(wb: ExcelJS.Workbook, marketplaces: readonly Marketplace[]): void {
  const ws = wb.addWorksheet('README');
  ws.columns = [{ width: 24 }, { width: 100 }];
  const head = (t: string) => {
    const r = ws.addRow([t, '']);
    r.getCell(1).font = { bold: true, size: 12 };
    r.getCell(1).alignment = { vertical: 'middle' };
  };
  const line = (a: string, b: string) => {
    const r = ws.addRow([a, b]);
    r.getCell(1).font = { bold: true };
    r.getCell(2).alignment = { wrapText: true, vertical: 'top' };
  };

  head('SALES TEMPLATE — same columns as the Sales Report');
  ws.addRow([]);
  line('What this is',
    `One sheet per marketplace (${marketplaces.join(', ')}), with exactly the columns the Sales `
    + 'Report exports. This file is generated FROM that report, so the two cannot drift apart.');
  line('The formulas are live',
    'Type a BP and an SP into a row and every derived column fills in immediately — SP-BP, '
    + 'Marginal Tax, Commission, the VAT lines, GP, GP % and Total VAT NTP. Rows you have not '
    + 'touched stay blank; they wake up as soon as the row has an SP.');
  line('What YOU fill in',
    'Date, Order Number, SKU, IMEI, Supplier, Quantity, BP, SP and Postage. On eBay also '
    + 'Marketing and P. VAT, and on Temu the Commission the marketplace actually charged — '
    + 'those cells carry no formula in the operator master either, because no formula can '
    + 'reproduce a figure the marketplace invoices per order.');
  line('What you leave alone',
    'Every other money column is a formula. Overwriting one replaces live maths with a frozen '
    + 'number that will not follow a price correction.');
  line('Row 2',
    'A worked example, filled in so you can see the formulas computing. Delete it or type over it.');
  line('Running out of rows',
    `${BLANK_ROWS} rows come primed. For more, select the last row and drag its fill handle down — `
    + 'the formulas carry themselves.');
  line('The TOTAL row',
    'At the foot of each sheet, summing the rows above it. If you drag past it, move it down.');
  line('Getting this back in',
    'Sales are recorded in the app under Sell → Mark Sold (or Mark Multiple Sold for one order '
    + 'covering several handsets). This file is a working sheet and a record, not an upload route.');
  ws.getRow(1).height = 22;
}

async function write(wb: ExcelJS.Workbook, name: string): Promise<void> {
  // Write once and COPY. Two writeFile calls produce two files that differ in
  // the zip's embedded timestamps, and templates.test.ts checks the served
  // copy is byte-identical to the one under test — for good reason: a public/
  // copy that has drifted hands operators a schema nothing else agrees with.
  await wb.xlsx.writeFile(`${OUT}/${name}`);
  copyFileSync(`${OUT}/${name}`, `${PUBLIC_OUT}/${name}`);
}

/** Drop every sheet that isn't in `keep`. */
function keepOnly(wb: ExcelJS.Workbook, keep: readonly string[]): void {
  for (const ws of [...wb.worksheets]) {
    if (!keep.includes(ws.name)) wb.removeWorksheet(ws.id);
  }
}

async function main(): Promise<void> {
  // ── combined: all five marketplaces in one file ──────────────────────
  const combined = await reportShapedWorkbook();
  keepOnly(combined, MARKETPLACES as readonly string[]);
  for (const ws of combined.worksheets) hollowOut(ws);
  addReadme(combined, MARKETPLACES);
  await write(combined, 'SALES_REPORT_TEMPLATE.xlsx');
  console.log(`SALES_REPORT_TEMPLATE.xlsx — ${combined.worksheets.length - 1} marketplace sheets`);

  // ── one file per marketplace ─────────────────────────────────────────
  for (const m of MARKETPLACES) {
    const wb = await reportShapedWorkbook();
    keepOnly(wb, [m]);
    for (const ws of wb.worksheets) hollowOut(ws);
    addReadme(wb, [m]);
    await write(wb, `SALES_${m}_TEMPLATE.xlsx`);
    const cols = ((wb.getWorksheet(m)!.getRow(1).values ?? []) as unknown[]).length - 1;
    console.log(`SALES_${m}_TEMPLATE.xlsx — ${cols} columns, ${BLANK_ROWS} primed rows`);
  }
}

main().catch(err => { console.error(err); process.exit(1); });
